spring:
  application:
    name: bff

server:
  port: ${SERVER_PORT:8081}

discovery:
  base-url: ${DISCOVERY_BASE_URL:http://127.0.0.1:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
