-- =============================================================================
-- BFF — V2 session store (I1-IAM-001)
-- Physical model per SEC-001 §5.3 (SEC-P01): one row per opaque BFF session.
--
-- Rules honoured here:
--   * Opaque session reference is the primary key (high-entropy random
--     value generated by the BFF; never a JWT or token material).
--   * OAuth token material is stored ONLY in encrypted, opaque form
--     (authenticated encryption with a versioned key ring; key material is
--     supplied via environment, never committed). No arbitrary Java
--     serialization anywhere in this store.
--   * Named constraints with stable names; no cross-service foreign keys
--     (AGENTS.md §4; ARC-022 §4).
--   * Keycloak subject is stored as the IdP subject identifier string —
--     no Account Service reference exists yet (I1-IAM-003 binds accounts).
-- =============================================================================
CREATE TABLE IF NOT EXISTS bff_session.bff_session (
    session_ref              text        NOT NULL
        CONSTRAINT ck_bff_session_ref_len CHECK (char_length(session_ref) >= 32),
    keycloak_subject         text        NOT NULL,
    keycloak_sid             text,
    encrypted_token_material bytea       NOT NULL,
    token_encryption_key_id  text        NOT NULL,
    acr                      text,
    authn_time               timestamptz NOT NULL,
    created_at               timestamptz NOT NULL,
    last_activity_at         timestamptz NOT NULL,
    idle_expires_at          timestamptz NOT NULL,
    absolute_expires_at      timestamptz NOT NULL,
    revocation_state         text        NOT NULL
        CONSTRAINT ck_bff_session_revocation_state
            CHECK (revocation_state IN ('ACTIVE', 'REVOKED')),
    security_event_metadata  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_bff_session PRIMARY KEY (session_ref)
);

-- Session lookup by subject + Keycloak session id (back-channel logout maps
-- IdP session id to local sessions; SEC-P01 §5.4).
CREATE INDEX IF NOT EXISTS idx_bff_session_subject_sid
    ON bff_session.bff_session (keycloak_subject, keycloak_sid);
